version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: ./services/api/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - db

  worker:
    build:
      context: .
      dockerfile: ./services/worker/Dockerfile
    depends_on:
      - redis
      - db

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: scanner
    ports:
      - "5432:5432"
    volumes:
      - ./infra/sql/init.sql:/docker-entrypoint-initdb.d/init.sql